### ISSUE TITLE
Compile fails ubuntu 16.04

### ISSUE THREAD

**Issue by crackfoo** [Actinium-project/Actinium-ng#5]
CXXLD    Actiniumd
tor/src/lib/libtor-process.a(setuid.o): In function `drop_capabilities':
/usr/local/src/Actinium-ng/src/tor/src/lib/process/setuid.c:196: undefined reference to `cap_get_proc'
/usr/local/src/Actinium-ng/src/tor/src/lib/process/setuid.c:202: undefined reference to `cap_clear'
/usr/local/src/Actinium-ng/src/tor/src/lib/process/setuid.c:204: undefined reference to `cap_set_flag'
/usr/local/src/Actinium-ng/src/tor/src/lib/process/setuid.c:205: undefined reference to `cap_set_flag'
/usr/local/src/Actinium-ng/src/tor/src/lib/process/setuid.c:206: undefined reference to `cap_set_flag'
/usr/local/src/Actinium-ng/src/tor/src/lib/process/setuid.c:208: undefined reference to `cap_set_proc'
/usr/local/src/Actinium-ng/src/tor/src/lib/process/setuid.c:209: undefined reference to `cap_free'
tor/src/lib/libtor-process.a(setuid.o): In function `have_capability_support':
/usr/local/src/Actinium-ng/src/tor/src/lib/process/setuid.c:152: undefined reference to `cap_get_proc'
/usr/local/src/Actinium-ng/src/tor/src/lib/process/setuid.c:155: undefined reference to `cap_free'
tor/src/lib/libtor-sandbox.a(sandbox.o): In function `sb_kill':
/usr/local/src/Actinium-ng/src/tor/src/lib/sandbox/sandbox.c:1126: undefined reference to `seccomp_rule_add'
tor/src/lib/libtor-sandbox.a(sandbox.o): In function `sb_ioctl':
/usr/local/src/Actinium-ng/src/tor/src/lib/sandbox/sandbox.c:743: undefined reference to `seccomp_rule_add'
tor/src/lib/libtor-sandbox.a(sandbox.o): In function `sb_socketpair':
/usr/local/src/Actinium-ng/src/tor/src/lib/sandbox/sandbox.c:724: undefined reference to `seccomp_rule_add'
tor/src/lib/libtor-sandbox.a(sandbox.o): In function `sb_stat64':
/usr/local/src/Actinium-ng/src/tor/src/lib/sandbox/sandbox.c:1106: undefined reference to `seccomp_rule_add'
tor/src/lib/libtor-sandbox.a(sandbox.o): In function `sb_mremap':
/usr/local/src/Actinium-ng/src/tor/src/lib/sandbox/sandbox.c:1081: undefined reference to `seccomp_rule_add'
tor/src/lib/libtor-sandbox.a(sandbox.o):/usr/local/src/Actinium-ng/src/tor/src/lib/sandbox/sandbox.c:957: more undefined references to `seccomp_rule_add' follow
tor/src/lib/libtor-sandbox.a(sandbox.o): In function `install_syscall_filter':
/usr/local/src/Actinium-ng/src/tor/src/lib/sandbox/sandbox.c:1526: undefined reference to `seccomp_init'
/usr/local/src/Actinium-ng/src/tor/src/lib/sandbox/sandbox.c:1563: undefined reference to `seccomp_release'
tor/src/lib/libtor-sandbox.a(sandbox.o): In function `prot_strings':
/usr/local/src/Actinium-ng/src/tor/src/lib/sandbox/sandbox.c:1308: undefined reference to `seccomp_rule_add'
/usr/local/src/Actinium-ng/src/tor/src/lib/sandbox/sandbox.c:1316: undefined reference to `seccomp_rule_add'
/usr/local/src/Actinium-ng/src/tor/src/lib/sandbox/sandbox.c:1333: undefined reference to `seccomp_rule_add'
/usr/local/src/Actinium-ng/src/tor/src/lib/sandbox/sandbox.c:1342: undefined reference to `seccomp_rule_add'
tor/src/lib/libtor-sandbox.a(sandbox.o): In function `add_noparam_filter':
/usr/local/src/Actinium-ng/src/tor/src/lib/sandbox/sandbox.c:1504: undefined reference to `seccomp_rule_add'
tor/src/lib/libtor-sandbox.a(sandbox.o): In function `install_syscall_filter':
/usr/local/src/Actinium-ng/src/tor/src/lib/sandbox/sandbox.c:1551: undefined reference to `seccomp_load'
/usr/local/src/Actinium-ng/src/tor/src/lib/sandbox/sandbox.c:1563: undefined reference to `seccomp_release'
collect2: error: ld returned 1 exit status
Makefile:4997: recipe for target 'Actiniumd' failed
make[2]: *** [Actiniumd] Error 1
make[2]: Leaving directory '/usr/local/src/Actinium-ng/src'
Makefile:13635: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/usr/local/src/Actinium-ng/src'
Makefile:781: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1

Any solution?

**Comment by brakmic** [comment]
GitHub is not for user support! Use our chats. Also, read our Wiki. The exact same problem has been described and solved there.

**Comment by crackfoo** [comment]
thanks always a pleasure
